

export default function RectanglePage() {
  return (
    <div className="bg-gray-800 h-screen w-screen grid grid-cols-[auto,1fr] p-8 gap-8">
      {/* Settings sidebar */}
      <div className="bg-gray-700 flex flex-col justify-between p-8 rounded-lg w-[120px]">
        <button className="bg-gray-600 p-4 text-white  mb-2">
          Home
        </button>
        <button className="bg-gray-600 p-4 text-white  mb-2">
          List
        </button>
        <button className="bg-gray-600 p-4 text-white ">
          Settings
        </button>
      </div>

      {/* Main content */}
      <div className="flex flex-col">
        {/* Top bar */}
        <div className="flex justify-between items-center mb-8">
          <p className="text-white text-2xl">8:00PM</p>
          <input
            type="text"
            placeholder="Search for a City..."
            className="p-2 bg-gray-700 rounded text-white focus:outline-none focus:border-white"
          />
        </div>

        <div className="flex-1 grid grid-cols-2 gap-8">
        {/* Main Left section */}
        <div className="grid grid-rows-3 gap-8">
            {/* City, Temperature & Today's Forecast */}
            <div className="bg-black p-8 rounded-lg flex flex-col justify-between row-span-2">
                <div>
                    <p className="text-white text-4xl mb-2">Pearland</p>
                    <p className="text-white text-6xl">85°F</p>
                </div>

                <div className="bg-[#0C1117] p-8 rounded-lg">
                    <p className="text-white text-2xl">TODAY’S FORECAST</p>
                </div>
            </div>

            {/* Air Conditions */}
            <div className="bg-gray-700 p-8 rounded-lg">
                <p className="text-white text-2xl">AIR CONDITIONS</p>
            </div>
        </div>

          {/* Main Right section */}
          <div className="grid grid-rows-2 gap-8">
            {/* ChatGPT block */}
            <div className="bg-white p-6 rounded-lg min-h-[300px]"> {/* Use the desired value in place of 300px */}
              <p className="text-gray-800 mb-2" style={{ fontSize: 'clamp(0.8rem, 3vw, 2rem)' }}>
                This evening in Pearland, Independence Park is open until 10:00 PM and offers a nice late-night option for a peaceful walk or some stargazing in a park setting.
              </p>
              <p className="text-gray-600 text-right text-sm">
                Suggestion Generated by ChatGPT
              </p>
            </div>

            {/* 7 Day Forecast */}
            <div className="bg-gray-700 p-8 rounded-lg min-h-[300px]"> {/* Use the desired value in place of 300px */}
              <p className="text-white text-2xl">7 DAY FORECAST</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
